[package]

name = "capnpc-newtype"
version = "0.27.0"
authors = [ "David Renshaw <dwrenshaw@gmail.com>", "Ben Jackson <puremourning@gmail.com>" ]
license = "MIT"
description = "Cap'n Proto code generation with newtype support"
repository = "https://github.com/puremourning/capnproto-rust"
documentation = "https://docs.rs/capnpc-newtype/"
edition = "2021"

readme = "README.md"

keywords = ["encoding", "protocol", "serialization"]

[lib]
name = "capnpc"

[[bin]]

name = "capnpc-rust"
path = "src/capnpc-rust.rs"

[[bin]]

name = "capnpc-rust-bootstrap"
path = "src/capnpc-rust-bootstrap.rs"


[dependencies.capnp]
package = "capnp-newtype"
version = "0.27.0"
path = "../capnp"

[lints]
workspace = true
